### ISSUE TITLE
'learn more' link on home page - Low

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfordMath_UAT#80]
learn more click from home page is opening very small popup. even the readability and font size is really small since it is a small pop up. can't we increase the pop up size?
![learn more](https://cloud.githubusercontent.com/assets/13584396/13176353/9fe9b0ac-d737-11e5-84bd-704756b9e50d.PNG)

**Comment by sumitmago** [comment]
hi Manas,
     could you please revert on the point raised above please?

**Comment by manasghosh81** [comment]
We have re-size the learn more .This will be available to UAT once we give another build .Please check this  after UAT deployment whether it  fulfills the change you are looking for.

**Comment by manasghosh81** [comment]
This fix is available in UAT. Please recheck

**Comment by sumitmago** [comment]
hi,
  What is the size increase that you have done? could you increase some more. it is still difficult to read/browse. fyi, I cleared browsing history as well.

**Comment by mouparnadas** [comment]
We have again resized and increased the learn more pop-up a bit more. Please review.

**Comment by sumitmago** [comment]
Dear Bindu/kasturi,
    Here is one feedback regarding Home Page -> ‘Learn More’ modal pop up that I gave. I suggested having a bigger modal pup up which TCS has done. I am ok with the s size but I am still not convinced about the readability aspect of the Text Size in modal pop up pages. Could I request you to please look at it and suggest weather it is per our standard guidelines that you shared earlier on Font Size and Font Style? 

![learn-more-modal pop up](https://cloud.githubusercontent.com/assets/13584396/13453367/8ff6a262-e075-11e5-8108-01a602cb4c00.PNG)

**Comment by sumitmago** [comment]
Remarks for TCS team -> could we give some border shade to images used in these modal pop up to differentiate between text write up and in line images? This would improve readability.

**Comment by CDS123** [comment]
Agreed with Sumit. Text should be highlighted and increase font size.—Bindu.

**Comment by manasghosh81** [comment]
@CDS123 @sumitmago @pkasturirangan : This is Subha, Can you please let us know what you meant by "text should be highlighted"?
- We are going to provide border / shadow to the images. Also please let us know the font and size to use, we will change accordingly. I guess the font the currently Verdana which is used throughout the site.

**Comment by CDS123** [comment]
My suggestion attached! (Bindu)
![model pop-up](https://cloud.githubusercontent.com/assets/17137588/13455747/4a9f52e4-e085-11e5-994f-313359341ca6.jpg)

**Comment by manasghosh81** [comment]
@sumitmago : This is done, please check.

**Comment by CDS123** [comment]
Wrong logo. Also having very poor quality. (Bindu)
![screen shot 2016-03-03 at 9 20 37 am](https://cloud.githubusercontent.com/assets/17137588/13484164/54f08d48-e121-11e5-91c5-a99f33ee18e3.png)

**Comment by sumitmago** [comment]
I saw and images are much better now. but somehow text is still small and difficult to read. this is the very first page of our site and lot of people will read these value streams (learn more on student, teacher etc.)
Are we ok with this size?

**Comment by manasghosh81** [comment]
@CDS123 : Hi Bindu, Regarding your comment, we are changing the logo, will inform you once done, however we cannot do anything on the clarity. The header part is very small and the logo will have to be made smaller to fit into the header, otherwise it will overlap with the content.

**Comment by sumitmago** [comment]
Hi Bindu,
               Is the current page – font size ok? I still feel it is small? Please check and let’s try to close ASAP.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by sumitmago** [comment]
@TCS - spoken to Bindu and he suggest to increase font size by 1 point. please do it and revert back with changes size in all three 'learn more' pages.

**Comment by mayank2k2** [comment]
@sumitmago , please take action on this

**Comment by sumitmago** [comment]
ok. closed.
